##################################AreaLand语言部分 & langguage ##############################
lang:
  ChangeLandMsg:
    Come: "&a你进入了 &6{LandName}&a."
    Leave: "&a你离开了 &7{LandName}&a."
  landUI: #领地UI界面
    OnOpen: "&6您打开了领地主界面."
    Title: "&b&l+领地信息+" #领地标题
    StickItem: #获取棍子的那一个格
      location: 41 #在箱子里的位置
      name: "&e获取圈地木棍" #名字
      lore: #Lore
        - "&b+单击获取圈地木棍+"
        - "&b注意: &7每分钟只能领取一次这个物品!"
        - "&b使用方法: &7左键选取点A 右键选取点B 即可圈地."
        - "&7圈地不是免费的 将会扣除你一定的金币."
        - "&7你可以在自己的领地上建造任何东西，不会被别人破坏!"
        - "&7你还可以把你的领地权限给你的好友,邀请他们一起来建筑!"
##################################AreaLand设定部分 & Settings ###############################
read:
  second: 1.5 #每几秒检测玩家所在的领地，越大耗能将会越小，并且数据越不精确