##################################AreaLand语言部分 & langguage ##############################
lang:
##################################AreaLand设定部分 & Settings ###############################
read:
  second: 1.5 #每几秒检测玩家所在的领地，越大耗能将会越小，并且数据越不精确